In [2]:
import numpy as np

In [8]:
np.mgrid[0:9, 0:6]


array([[[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8]],

       [[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]]])

In [9]:
np.mgrid[0:9, 0:6].T



array([[[0, 0],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0],
        [5, 0],
        [6, 0],
        [7, 0],
        [8, 0]],

       [[0, 1],
        [1, 1],
        [2, 1],
        [3, 1],
        [4, 1],
        [5, 1],
        [6, 1],
        [7, 1],
        [8, 1]],

       [[0, 2],
        [1, 2],
        [2, 2],
        [3, 2],
        [4, 2],
        [5, 2],
        [6, 2],
        [7, 2],
        [8, 2]],

       [[0, 3],
        [1, 3],
        [2, 3],
        [3, 3],
        [4, 3],
        [5, 3],
        [6, 3],
        [7, 3],
        [8, 3]],

       [[0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4]],

       [[0, 5],
        [1, 5],
        [2, 5],
        [3, 5],
        [4, 5],
        [5, 5],
        [6, 5],
        [7, 5],
        [8, 5]]])

In [10]:
np.mgrid[0:9, 0:6].T.reshape(-1, 2)


array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [6, 0],
       [7, 0],
       [8, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [7, 1],
       [8, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [5, 2],
       [6, 2],
       [7, 2],
       [8, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [5, 3],
       [6, 3],
       [7, 3],
       [8, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [5, 4],
       [6, 4],
       [7, 4],
       [8, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [5, 5],
       [6, 5],
       [7, 5],
       [8, 5]])

In [14]:
a = np.arange(6).reshape((1, 6))
a

array([[0, 1, 2, 3, 4, 5]])

In [15]:
np.reshape(a, (-1,2)) 

array([[0, 1],
       [2, 3],
       [4, 5]])

This distortion can be corrected by the following system of equations:

$$x_{distorted} = x( 1 + k_1 r^2 + k_2 r^4 + k_3 r^6)$$

$$y_{distorted} = y( 1 + k_1 r^2 + k_2 r^4 + k_3 r^6)$$

Similarly, another type of distortion is tangential distortion that occurs because the image capture lens is not aligned perfectly parallel to the imaging plane. As a result, some areas in the image may appear closer than expected. It is expressed as follows:

$$x_{distorted} = x + [ 2p_1xy + p_2(r^2+2x^2)]$$

$$y_{distorted} = y + [ p_1(r^2+ 2y^2)+ 2p_2xy]$$

In short, we need to find five parameters, called distortion coefficients, given by:

$$Distortion \; coefficients=(k_1 \hspace{10pt} k_2 \hspace{10pt} p_1 \hspace{10pt} p_2 \hspace{10pt} k_3)$$

In addition to this, we need to find more information, such as the internal and external parameters of the camera. Internal parameters are specific to the camera. It includes information such as focal length ($f_x, f_y$), optical center ($c_x, c_y$). It is also called the camera matrix and depends only on the camera, so it can be calculated only once and then stored for future use. It is represented as a 3x3 matrix:

$$camera \; matrix = \left [ \begin{matrix} f_x & 0 & c_x \ 0 & f_y & c_y \ 0 & 0 & 1 \end{matrix} \right ]$$

The extrinsic parameters correspond to the rotation vector and translation vector, which can transform the coordinates of the 3D point into the coordinate system.

In 3D related applications, these distortions must first be corrected. In order to find these parameters, we have to provide some sample images that contain obvious pattern patterns (say a checkerboard). We can find some special points on it (such as the four corners of the chessboard). We figured out where these particular points are in the picture and where they really are. Armed with this information, we can solve for the distortion coefficients mathematically. This is the summary of the whole story. For better results, we need at least 10 such pattern patterns.